# Generated by Django 4.1.5 on 2023-08-05 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailypulse', '0002_new_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_id',
            new_name='news_id',
        ),
    ]
