# Generated by Django 4.1.5 on 2023-08-05 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dailypulse', '0003_rename_post_id_comment_news_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='news_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dailypulse.new'),
        ),
    ]
