# Generated by Django 4.1.5 on 2023-08-05 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailypulse', '0004_alter_comment_news_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='news_id',
            new_name='news',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
    ]
