# Generated by Django 4.1.5 on 2023-08-05 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailypulse', '0002_reading_later'),
        ('dailypulse', '0006_news_alter_comment_news_delete_new'),
    ]

    operations = [
    ]
