# Generated by Django 4.1.5 on 2023-08-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailypulse', '0007_merge_20230805_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reading_later',
            old_name='reviewer',
            new_name='user',
        ),
        migrations.AddField(
            model_name='reading_later',
            name='author',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='reading_later',
            name='published_date',
            field=models.DateField(default='1996-07-30'),
        ),
        migrations.AddField(
            model_name='reading_later',
            name='source',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='reading_later',
            name='url_image',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
