# Generated by Django 4.1.5 on 2023-08-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailypulse', '0011_alter_comment_user_alter_news_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='newsTitle',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='userName',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
